import { describe, expect, it } from "vitest";
import { CANONICAL_ORIGIN, noindex, robotsTxt, sitemapXml } from "../src/index";

/**
 * Three names answer this Worker - textrelay.cc, relay.supr.systems and the
 * workers.dev fallback - and all three serve byte-identical HTML. To a crawler
 * that is the same site published at three addresses, which is the one thing a
 * brand-new domain cannot afford: whichever copy it picks is the one that
 * ranks, and it will not pick the one on the business card.
 *
 * And /watch/<token> must never be indexed at all. The token is the whole
 * credential, the pages are generated by the thousand, and every link pasted
 * into a public Discord is one a crawler can reach.
 */

const url = (u: string) => new URL(u);

describe("robots.txt", () => {
  it("points a crawler at the sitemap on the canonical name", () => {
    const txt = robotsTxt(url("https://textrelay.cc/robots.txt"));
    expect(txt).toContain(`Sitemap: ${CANONICAL_ORIGIN}/sitemap.xml`);
    expect(txt).toMatch(/^Allow: \/$/m);
  });

  it("keeps crawlers out of the viewer pages", () => {
    expect(robotsTxt(url("https://textrelay.cc/robots.txt"))).toMatch(/^Disallow: \/watch\//m);
  });

  it("refuses the whole site on every name that is not the canonical one", () => {
    // relay.supr.systems and the workers.dev fallback serve the same HTML.
    // Left crawlable they compete with textrelay.cc for its own pages.
    for (const host of ["https://relay.supr.systems", "https://callout-relay-hosted.workers.dev"]) {
      const txt = robotsTxt(url(`${host}/robots.txt`));
      expect(txt, host).toMatch(/^Disallow: \/$/m);
      expect(txt, host).not.toContain("Sitemap:");
    }
  });
});

describe("sitemap.xml", () => {
  it("lists the home page, absolutely and on the canonical name", () => {
    const xml = sitemapXml();
    expect(xml).toContain(`<loc>${CANONICAL_ORIGIN}/</loc>`);
    expect(xml.startsWith("<?xml")).toBe(true);
  });

  it("lists no viewer page, ever", () => {
    expect(sitemapXml()).not.toContain("/watch/");
  });
});

describe("noindex", () => {
  it("adds the header to a response whose own headers are immutable", () => {
    // env.ASSETS.fetch() hands back a response with a locked header list, so
    // setting the header on it in place throws. This is why the response is
    // rebuilt rather than mutated.
    const asset = new Response("<!doctype html>", {
      status: 200,
      headers: new Headers({ "content-type": "text/html" }),
    });
    Object.defineProperty(asset.headers, "set", {
      value: () => {
        throw new TypeError("immutable");
      },
    });

    const out = noindex(asset);
    expect(out.headers.get("X-Robots-Tag")).toBe("noindex, nofollow");
    expect(out.headers.get("content-type")).toBe("text/html");
    expect(out.status).toBe(200);
  });
});
