/**
 * Where a plain-HTTP request should be sent instead, or undefined to serve it.
 *
 * A viewer link is `<origin>/watch/<viewerToken>` and that token is the whole
 * credential - no password, no expiry, no device check - so over HTTP it
 * crosses the wire in the request line, in clear. Nothing was redirecting: all
 * three names answered 200 on port 80 with the real page and no HSTS.
 *
 * Here rather than in Cloudflare's zone setting, so it travels with the code
 * and covers every name the Worker answers on, including ones added later.
 *
 * Two things are deliberately left alone. A WebSocket upgrade cannot follow a
 * 301, so redirecting one turns a working socket into a silent failure - and
 * the app dials `wss://` anyway. And loopback is how `wrangler dev` serves,
 * where there is no certificate to redirect to.
 */
const LOOPBACK = new Set(["localhost", "127.0.0.1", "::1", "[::1]"]);

export function insecureRedirect(url: URL, upgrade: string | null): string | undefined {
  if (url.protocol !== "http:") return undefined;
  if ((upgrade || "").toLowerCase() === "websocket") return undefined;
  if (LOOPBACK.has(url.hostname)) return undefined;
  const secure = new URL(url.toString());
  secure.protocol = "https:";
  return secure.toString();
}

/**
 * Where a request goes, decided from the path alone.
 *
 * Pure on purpose: this is the half of the service that can be wrong in a way
 * no amount of Cloudflare-side testing catches quickly, and it has to agree
 * exactly with the single-tenant relay it replaces (packages/relay/src/server.ts
 * lines 469-495) or the viewer breaks in a way that only shows up in OBS.
 *
 * The asset rule is the subtle one. The shipped viewer page references its
 * assets RELATIVELY:
 *
 *   <link rel="stylesheet" href="fonts/fonts.css" />
 *   <link rel="stylesheet" href="style.css" />
 *   <script src="app.js"></script>
 *
 * so a page served at /watch/<token> asks for /watch/style.css. Tokens cannot
 * contain a dot and filenames always do, which is exactly how the existing
 * relay tells them apart. Get this wrong and the overlay serves a bare
 * unstyled page with no script - the failure looks like a broken relay.
 */

export type Route =
  | { kind: "home" }
  | { kind: "viewer-page"; token: string }
  | { kind: "asset"; rel: string }
  | { kind: "ws-uplink" }
  | { kind: "ws-viewer" }
  | { kind: "health" }
  | { kind: "claim" }
  | { kind: "feedback" }
  | { kind: "viewer-token" }
  | { kind: "rotate-viewer-token" }
  /** the version the landing page reads, and the installer its button points at */
  | { kind: "update-feed" }
  | { kind: "download" }
  /** the two files a crawler looks for before it trusts anything else here */
  | { kind: "sitemap" }
  | { kind: "robots" }
  | { kind: "not-found" };

/**
 * The installer filename out of an electron-updater `latest.yml`.
 *
 * Line-oriented rather than a YAML parse: the file is four fields written by
 * electron-builder, and pulling in a parser to read one of them would be the
 * larger risk. Returns undefined rather than guessing, and the caller sends
 * people to the releases page when it does.
 */
export function installerName(feed: string): string | undefined {
  for (const line of feed.split(/\r?\n/)) {
    const m = /^\s*path:\s*(\S+)\s*$/.exec(line);
    if (m) return m[1];
  }
  return undefined;
}

/**
 * The files the landing page and a browser ask for at the root, by name.
 *
 * An allowlist rather than a prefix rule, for the same reason /updates/ is not
 * one: the asset directory is the viewer bundle the desktop app also ships,
 * and a rule like "serve any file at the root" publishes whatever lands in it
 * next. Adding a file here is a deliberate act.
 */
const ROOT_ASSETS = new Set(["og.png", "favicon.svg", "favicon.ico", "apple-touch-icon.png"]);

/** a token is [A-Za-z0-9_-]+ with no dot; a filename always has one */
const TOKEN_PATH = /^\/watch\/([A-Za-z0-9_-]+)$/;

export function resolveRoute(pathname: string, method = "GET"): Route {
  if (pathname === "/health") return { kind: "health" };
  // Exactly these two, not a `/updates/` prefix. The Node relay serves a
  // directory there; the Worker has no directory and should not look as though
  // it might - a prefix match invites probing for one.
  if (pathname === "/updates/latest.yml") return { kind: "update-feed" };
  if (pathname === "/download") return { kind: "download" };
  if (pathname === "/ws/uplink") return { kind: "ws-uplink" };
  // Generated by the Worker, not served from the asset directory: that
  // directory is also the bundle the desktop app ships, and a robots.txt
  // naming textrelay.cc has no business inside a local relay on port 8787.
  if (pathname === "/sitemap.xml") return { kind: "sitemap" };
  if (pathname === "/robots.txt") return { kind: "robots" };
  if (pathname === "/ws/viewer") return { kind: "ws-viewer" };

  if (pathname === "/claim") return method === "POST" ? { kind: "claim" } : { kind: "not-found" };
  // a report a person chose to send; GET (or anything else) 404s the same
  // way the other write-only routes above do
  if (pathname === "/feedback") return method === "POST" ? { kind: "feedback" } : { kind: "not-found" };
  if (pathname === "/admin/viewer-token") {
    return method === "GET" ? { kind: "viewer-token" } : { kind: "not-found" };
  }
  if (pathname === "/admin/rotate-viewer-token") {
    return method === "POST" ? { kind: "rotate-viewer-token" } : { kind: "not-found" };
  }

  if (pathname.startsWith("/") && ROOT_ASSETS.has(pathname.slice(1))) {
    return { kind: "asset", rel: pathname.slice(1) };
  }

  if (pathname === "/" || pathname === "/watch" || pathname === "/watch/") return { kind: "home" };

  const watch = TOKEN_PATH.exec(pathname);
  if (watch) return { kind: "viewer-page", token: watch[1] };

  // /watch/style.css, /watch/app.js, /watch/fonts/fonts.css
  if (pathname.startsWith("/watch/")) {
    const rel = pathname.slice("/watch/".length);
    return safeRel(rel) ? { kind: "asset", rel } : { kind: "not-found" };
  }
  // the landing page loads fonts from the root, the viewer from /watch/
  if (pathname.startsWith("/fonts/")) {
    const rel = pathname.slice(1);
    return safeRel(rel) ? { kind: "asset", rel } : { kind: "not-found" };
  }

  return { kind: "not-found" };
}

/** no traversal, no absolute paths, no empty segments */
function safeRel(rel: string): boolean {
  if (!rel || rel.startsWith("/")) return false;
  return rel.split("/").every((seg) => seg.length > 0 && seg !== "." && seg !== "..");
}
